buildscript {
    repositories {
        // Прямая ссылка на Google Maven
        maven { url 'https://maven.google.com' }
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath 'com.google.gms:google-services:4.3.15'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.5'
    }
}

allprojects {
    repositories {
        maven { url 'https://maven.google.com' }
        mavenCentral()
    }
}
